### PR TITLE
Feature/adding Vietnamese

### PR DESCRIPTION
**Pull request by duongnv1996**
Hi team,
I've  just translate language to Vietnamese.
Here is some screenshot,
I don't know why some text was not changed.

Screenshot_20210913_173550
Screenshot_20210913_173521
Screenshot_20210913_173503

### CODE REVIEW

**Comment by LagradOst** [comment]
Remove the keys

**Comment by LagradOst** [comment]
Also it seams like you have not copied some things, like swipe_to_change_settings and swipe_to_change_settings_des or updates_settings and updates_settings_des and that is why not everything is translated. As for description and tags/genres are not translated because they come from the site itself.

**Comment by duongnv1996** [comment]
> Also it seams like you have not copied some things, like swipe_to_change_settings and swipe_to_change_settings_des or updates_settings and updates_settings_des and that is why not everything is translated. As for description and tags/genres are not translated because they come from the site itself.

Thanks. I commit new string . It's work well now

**Comment by LagradOst** [comment]
Ready to merge?

**Comment by duongnv1996** [comment]
> Ready to merge?

yes

**Pull request merged**
