### PR TITLE
Redesign player layout for tv

### PR DESCRIPTION
**Pull request by doteq**
I redesigned player for TV, because it had bad UX (hard to spot selected element, and navigating was really difficult). Now it's more like netflix UI, you don't need to navigate through whole UI just to pause player. 
image

Major changes in navigation:

- UI hidden
  - Center button: pause player and show ui
  - Right button: fast-forward video by 10 seconds
  - Left button: rewind video by 10 seconds
- UI visible
  - Progress bar is no longer focusable
  - When pause/play button is focused, right and left buttons seeks by 30 seconds
  - Increased visibility of bottom buttons

### CODE REVIEW

**Comment by LagradOst** [comment]
10/10 pr, just going to change some cs3 related stuff

**Comment by LagradOst** [comment]
https://github.com/doteq/CloudStream-3/pull/1

**Comment by LagradOst** [comment]
Ready to merge?

**Comment by Blatzar** [comment]
Thank you very cool.

**Pull request merged**
