### PR TITLE
Added Egy.best

### PR DESCRIPTION
**Pull request by ImZaw**

### CODE REVIEW

**Comment by cutterchop** [comment]
!!! @eigengravy eigen best O_O ?

**Comment by LagradOst** [comment]
LGTM, however with pairs you can do. apmap { (name, url) -> instead of first and second

**Comment by ImZaw** [comment]
> LGTM, however with pairs you can do. apmap { (name, url) -> instead of first and second

wait wdym where?

**Comment by LagradOst** [comment]
@ImZaw here is an example https://github.com/LagradOst/CloudStream-3/blob/391215d76f88bf109b66dcfa959d6eff618e0905/app/src/main/java/com/lagradost/cloudstream3/animeproviders/NineAnimeProvider.kt#L31

**Comment by ImZaw** [comment]
> @ImZaw here is an example
> 
> https://github.com/LagradOst/CloudStream-3/blob/391215d76f88bf109b66dcfa959d6eff618e0905/app/src/main/java/com/lagradost/cloudstream3/animeproviders/NineAnimeProvider.kt#L31

like this?

**Comment by ImZaw** [comment]
> > @ImZaw here is an example
> > https://github.com/LagradOst/CloudStream-3/blob/391215d76f88bf109b66dcfa959d6eff618e0905/app/src/main/java/com/lagradost/cloudstream3/animeproviders/NineAnimeProvider.kt#L31
> 
> like this?

ouch forgot that ->

**Comment by LagradOst** [comment]
LGTM, ready to merge?

**Comment by ImZaw** [comment]
> LGTM, ready to merge?

Yea 👍

**Pull request merged**
