### PR TITLE
tr translation

### PR DESCRIPTION
**Pull request by vanhoxx**
finally managed to translate :)

### CODE REVIEW

**Comment by cutterchop** [comment]
Brother I told you don't translate the disclaimer it's not translatable

**Comment by vanhoxx** [comment]
> Brother I told you don't translate the disclaimer it's not translatable

Ok i reverted.

**Comment by cutterchop** [comment]
> > Brother I told you don't translate the disclaimer it's not translatable
> 
> Ok i reverted.

Alhamdulialh 1 year pr fixed??

**Comment by vanhoxx** [comment]
> > > Brother I told you don't translate the disclaimer it's not translatable
> > 
> > Ok i reverted.
> 
> Alhamdulialh 1 year pr fixed?? 

Too much hardwork, big contribution to the community habibi :)

**Comment by Blatzar** [comment]
Is this ready for merge? @vanhoxx

**Comment by vanhoxx** [comment]
> Is this ready for merge? @vanhoxx 

Yes

**Comment by cutterchop** [comment]
All checks have failed wha-

**Comment by Blatzar** [comment]
image

**Comment by vanhoxx** [comment]
> image
> 

Didn't understand what does that mean, i just translated the translatable that's all.

**Comment by vanhoxx** [comment]
So the problem is the existence of "do not translate" section and my fault not using \ before ' thank you for the correction

**Pull request merged**
