### PR TITLE
Update EgyBestProvider.kt

### PR DESCRIPTION
**Pull request by odnar-dev**
scrape egybest home page and show the same categories as the site

### CODE REVIEW

**Comment by zozo11299** [comment]
Doesn't the app scrape the home page already? Also take a look into adding Cast feature egy best has it so you can do it

**Comment by LagradOst** [comment]
@ImZaw Can you take a look at this

**Comment by ImZaw** [comment]
> @ImZaw Can you take a look at this

LGTM i think

**Comment by LagradOst** [comment]
LGTM, ready to merge? 👍

**Comment by odnar-dev** [comment]
ready to merge :+1:

**Comment by maherhosny** [comment]
some movies and serieses has no subtitles can u add cc button to the player with subscene and opensubtitles links.

**Pull request merged**
