### PR TITLE
Indonesian translation

### PR DESCRIPTION
**Pull request by exsolvere**

### CODE REVIEW

**Comment by exsolvere** [comment]
Hey, sorry if I'm doing anything wrong, I am really new.

**Comment by LagradOst** [comment]
@exsolvere It looks correct, however simply adding the file will sadly not work in the app. You will have to add it here https://github.com/LagradOst/CloudStream-3/blob/master/app/src/main/java/com/lagradost/cloudstream3/ui/settings/SettingsLang.kt#L25 and if you want people looking at the app to also see it you have to add it in the readme https://github.com/LagradOst/CloudStream-3/blob/master/README.md

Also, can you remove the lines 3 to 53 as it contains keys and should not be translated

**Comment by exsolvere** [comment]
does that work?

**Comment by LagradOst** [comment]
Yes, that should be it, waiting for the autobuild to check code, then I can merge

**Comment by LagradOst** [comment]
Do you want to merge now or is there any last addition things you want to change?

**Comment by exsolvere** [comment]
That should be all, you can merge

**Pull request merged**
