### PR TITLE
chore: Added Pt & Ro Translations

### PR DESCRIPTION
**Pull request by Darthagnon**
Added Pt-Br and Ro languages. Issue: https://github.com/LagradOst/CloudStream-3/issues/263

Essential checks:
- ```Pt-Br``` language code, is it too long? or shorten to just Pt.
- filenames. I based the xml off the Spanish one, only to find that some are called ```strings-[language code].xml``` and others just ```strings.xml```
- I corrected 2 flag bytecodes. Did that break anything?

Optional checks:
- Check Romanian with a native speaker. Better to have a bad translation than none at all, though.
- Double-check Pt-Br; as it is very similar to Spanish, I might have missed something.

### CODE REVIEW

**Comment by Darthagnon** [comment]
Issue:
https://github.com/LagradOst/CloudStream-3/issues/263

**Comment by LagradOst** [comment]
Nice, however the suffix of strings.xml and Triple("\ud83c\udde7\ud83c\uddf7", "Portuguese (Brazil)", "**pt-br**"), must be the same. so change pt-br to pt in strings.xml or settings in order to make it work. 👍

**Comment by Darthagnon** [comment]
Should be fixed. I don't have a dev environment for this, so haven't tested, though.

**Comment by LagradOst** [comment]
LGTM, ready to merge?

**Comment by ArjixWasTaken** [comment]
If the build passes then yes.

**Comment by ArjixWasTaken** [comment]
> Should be fixed. I don't have a dev environment for this, so haven't tested, though.

It's fairly easy, you just have to install Android Studio (its quite chunky in size).
But in this case since it's just a translation, any errors should be caught by the github tests.

**Comment by Darthagnon** [comment]
I guess it's okay to delete the branch now? Still learning my way around Github. Thank you for the opportunity to contribute!

**Pull request merged**
