### PR TITLE
site list changes

### PR DESCRIPTION
**Pull request by C10udburst**
- made site-list.json automatically create providers.json (new providers will be marked as beta)
- removed site list from readme (now shows a link)
- remove jquery dependency and split src into multiple files

### CODE REVIEW

**Comment by LagradOst** [comment]
I dont get it

**Comment by LagradOst** [comment]
can you explain exactly how the json is generated, I am illiterate in python and regex

**Comment by C10udburst** [comment]
this is what it essentially does:
- load previous list
- find all *Provider.kt
- for each found provider:
	- find the name and url
	- if entry was on the previous list, use that entry
	- if not, create a new entry with status 3
- add remaining providers from the previous list
- write to the `./docs/providers,json` file

**Comment by LagradOst** [comment]
So it keeps the status of the previous entry? Also I think it is better to just set it to status 1 as status 3 is only used when a provider is semi working

**Comment by LagradOst** [comment]
@C10udburst Does it keep the previous status value?

**Pull request merged**
