### PR TITLE
More informative issue template

### PR DESCRIPTION
**Pull request by OshekharO**

### CODE REVIEW

**Comment by LagradOst** [comment]
No, I dont want ppl to create issues for source request

**Comment by OshekharO** [comment]
@LagradOst now you can merge as i have deleted source request template

**Comment by LagradOst** [comment]
Damn, this looking hella fine. Tho I would replace `I have updated the app to version **[Latest](https://github.com/LagradOst/CloudStream-3/releases)**.` to smth like `This issue also exist on the latest pre-release version **[Latest](https://github.com/LagradOst/CloudStream-3/releases/tag/pre-release)**.` as things are often fixed in the pre-release but not stable

**Comment by LagradOst** [comment]
Many issues are are provider specific so an optional tag for that as well

**Comment by OshekharO** [comment]
> Many issues are are provider specific so an optional tag for that as well, - Provider: [e.g. https://trailers.to/en/movie/4391225/red-notice-2021]

Should I make new template for provider related issues or just in issue template should I add line asking whether it's provider related issue or not?

**Comment by LagradOst** [comment]
> > Many issues are are provider specific so an optional tag for that as well, - Provider: [e.g. https://trailers.to/en/movie/4391225/red-notice-2021]
> 
> Should I make new template for provider related issues or just in issue template should I add line asking whether it's provider related issue or not?

Might be a good idea to separate as some of the questions might be a bit redundant. (how to replicate: go into the provider x and y does not work <- this is useless)

**Comment by OshekharO** [comment]
> > > Many issues are are provider specific so an optional tag for that as well, - Provider: [e.g. https://trailers.to/en/movie/4391225/red-notice-2021]
> > 
> > 
> > Should I make new template for provider related issues or just in issue template should I add line asking whether it's provider related issue or not?
> 
> Might be a good idea to separate as some of the questions might be a bit redundant. (how to replicate: go into the provider x and y does not work <- this is useless)

Now I think it's ready to be merged.

**Pull request merged**
