### PR TITLE
Add default cover when posterUrl is null or empty

### PR DESCRIPTION
**Pull request by Jacekun**
- Add 'No Episodes found' on series when episode count is 0

### CODE REVIEW

**Comment by LagradOst** [comment]
ye, we will have to change the default cover if this ever gonna get merged

**Comment by Jacekun** [comment]
> ye, we will have to change the default cover if this ever gonna get merged

Any suggestions to what cover to use?

**Comment by LagradOst** [comment]
I can design an svg

**Comment by LagradOst** [comment]
smth like this?
no_poster

**Comment by Jacekun** [comment]
lgtm, maybe only highlight the color of the center pic

**Comment by LagradOst** [comment]
add this as a drawable xml and change the color
[vd_vector.txt](https://github.com/LagradOst/CloudStream-3/files/7846069/vd_vector.txt)

**Pull request merged**
