### PR TITLE
Translatable Readme & Spanish Translation

### LINKED ISSUE #107: Translated to Spanish

### PR DESCRIPTION
**Pull request by another-sapiens**
Hi there! Your app's in Spanish now. 
Should close #107 

Is there a way to translate the Readme, by the way?

### CODE REVIEW

**Comment by LagradOst** [comment]
Looks good, but if you want it in settings you got to add it here https://github.com/LagradOst/CloudStream-3/blob/6a561a35c0d7ae766f099ccd1aeafbdb4a32bbeb/app/src/main/java/com/lagradost/cloudstream3/ui/settings/SettingsFragment.kt#L30

**Comment by LagradOst** [comment]
I think the readme cant be translated. But you might also want to add Spanish in the readme list.

**Comment by another-sapiens** [comment]
I just added it in the settings and the readme, should be all set up

**Comment by LagradOst** [comment]
Wonderfull, can I merge or do you want to change anything?

**Comment by another-sapiens** [comment]
I just added the /fastlane/metadata/android/ structure F-Droid needs. In theory translations should work now...?

I'm a noob at this, first time I try it, so I don't know if it'll do anything. Won't hurt to try though. 
We should merge it and see if it works.  ^^

**Pull request merged**
