### PR TITLE
Subtitle transparency

### PR DESCRIPTION
**Pull request by AbdullahM0hamed**

### CODE REVIEW

**Comment by LagradOst** [comment]
Can you add this to all color stuff in the subs?

**Comment by AbdullahM0hamed** [comment]
OK so it appears that the outline is just a bigger version of the same text (which works normally, because the non-outline bit is hidden behind the text colour) - so this means that in order for this to work both the text colour AND the outline colour must have some transparency

Fully transparent text colour + fully opaque outline:
Screenshot_20211117-115924_CloudStream Debug

Fully transparent text colour + semi transparent outline:
Screenshot_20211117-115933_CloudStream Debug

**Comment by AbdullahM0hamed** [comment]
> Can you add this to all color stuff in the subs?

From what I can tell - it has affected them:
Screenshot_20211117-120411_CloudStream Debug

**Comment by LagradOst** [comment]
The more options the better, (the og request was for transparent bg)

**Comment by moenkaey** [comment]
i am a monke

**Pull request merged**
