### PR TITLE
Create GitHub workflows

### PR DESCRIPTION
**Pull request by C10udburst**
- `pull_request.yml` - will be run on all pull request, the debug apk will be send to artifacts
- `prerelease.yml` - will run on pushes to the master branch of the repository, the debug apk will be send to pre-release in releases. the previous pre-release will be replaced.

There's a setting to make in app updater use prereleases instead of full releases

Current prerelease commit hash gets stored in `R.string.prerelease_commit_hash` and that's what gets compared to github newest prerelease tag

### CODE REVIEW

**Comment by LagradOst** [comment]
wow this looks 🔥

**Comment by Blatzar** [comment]
wtf nice

**Comment by ArjixWasTaken** [comment]
Woah
This got even better in the span of a single day.

**Comment by LagradOst** [comment]
wtf, you can improve upon perfection???

**Comment by LagradOst** [comment]
Looks good to me

**Pull request merged**
