### PR TITLE
Key fixes

### LINKED ISSUE #1095: Vidstream and Mcloud not Working Again
### Steps to reproduce

Try playing anything in 9anime, Sflix.pro, Bflix etc

### Expected behavior

Vidstream and Mcloud Links Show and Play 

### Actual behavior

No Vidstream and Mcloud Links 

### Cloudstream version

2.10.25

### Android version

Android 9

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/LagradOst/CloudStream-3/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by Stormunblessed**
Thanks to @Modder4869 for helping with keys
Made a helper for getting keys
Made a txt file with the key
Modified prerelease.yml so when key changes, building it's not required, also no need to install an update
Closes #1095

### CODE REVIEW

**Comment by LagradOst** [comment]
No, do it by lazy instead. I dont want to ddos github for no reason

**Comment by Stormunblessed** [comment]
> 

don't know how to do that

**Comment by LagradOst** [comment]
The easiest way is to have a private nullable string and getWcoKey simply returns smth like key ?: run {
key = ...
key
}

**Comment by LagradOst** [comment]
hmm, I think there might be other keys in the future, what about expanding it to a json instead?

**Comment by Blatzar** [comment]
> don't know how to do that
```kotlin
val keyJson by lazy {
// code
}
```

**Comment by LagradOst** [comment]
> > don't know how to do that
> 
> ```kotlin
> val keyJson by lazy {
> // code
> }
> ```

it is suspended, that might fuck it

**Comment by Blatzar** [comment]
> it is suspended, that might fuck it

runBlocking { } always exists :shrug:

**Pull request merged**
